version: "3.3"
services:
  app:
    build: .
    container_name: app
    ports: 
      - "9090:8081"
    links:
      -"mongodb"
  mongodb:
    image: mongo
    container-container_name: mongodb
    ports: 
      -"27017:27017"
    
